version: '3'
services:
  postgres:
    build:
      context: ./data
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  omo-auth:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - "5000:5000"

volumes:
  postgres: ~
